In [1]:
from sklearn.datasets import load_iris
iris = load_iris()
print(iris.data)
print(iris.target)
print(iris.data.shape)
print(iris.target_names)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [3]:
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_iris

iris = load_iris()
print('the data size of iris：',iris.data.shape)
print('the size of target dataset：',iris.target.shape)
X_train,X_test,Y_train,Y_test = train_test_split(iris.data,iris.target,test_size = 0.4,random_state = 0)

print('生成的训练集的特征个数（数据个数）：',X_train.shape)
print('生成的训练集的标签个数（样本个数）：',Y_train.shape)
print('生成的测试集的特征（数据个数）：',X_test.shape)
print('生成的测试集的标签个数（样本个数）：',Y_test.shape)
print('iris数据集前5行的数据：',iris.data[:5])
print('生成的训练集的前5行的数据：',X_train[:5])

the data size of iris： (150, 4)
the size of target dataset： (150,)
生成的训练集的特征个数（数据个数）： (90, 4)
生成的训练集的标签个数（样本个数）： (90,)
生成的测试集的特征（数据个数）： (60, 4)
生成的测试集的标签个数（样本个数）： (60,)
iris数据集前5行的数据： [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
生成的训练集的前5行的数据： [[6.  3.4 4.5 1.6]
 [4.8 3.1 1.6 0.2]
 [5.8 2.7 5.1 1.9]
 [5.6 2.7 4.2 1.3]
 [5.6 2.9 3.6 1.3]]


In [4]:
from sklearn.model_selection import cross_val_score
from sklearn.datasets import load_iris
from sklearn import svm
iris = load_iris()
# 使用支持向量机模型进行验证
clf = svm.SVC(kernel='linear',C=1)
# 进行5折交叉验证
scores = cross_val_score(clf,iris.data,iris.target,cv=5)
print(scores)
print(scores.mean())

[0.96666667 1.         0.96666667 0.96666667 1.        ]
0.9800000000000001


In [5]:
import numpy as np
from sklearn.model_selection import KFold

X = ['a','b','c','d','e','f']
# 进行2折交叉验证
kf = KFold(n_splits=2)
# 输出拆分结果
for train,test in kf.split(X):
    print(train,test)
    print(np.array(X)[train],np.array(X)[test])

[3 4 5] [0 1 2]
['d' 'e' 'f'] ['a' 'b' 'c']
[0 1 2] [3 4 5]
['a' 'b' 'c'] ['d' 'e' 'f']


In [6]:
import numpy as np
from sklearn.model_selection import LeaveOneOut

X = ['a','b','c','d','e','f']
loo = LeaveOneOut()
for train,test in loo.split(X):
    print(train,test)
    print(np.array(X)[train],np.array(X)[test])

[1 2 3 4 5] [0]
['b' 'c' 'd' 'e' 'f'] ['a']
[0 2 3 4 5] [1]
['a' 'c' 'd' 'e' 'f'] ['b']
[0 1 3 4 5] [2]
['a' 'b' 'd' 'e' 'f'] ['c']
[0 1 2 4 5] [3]
['a' 'b' 'c' 'e' 'f'] ['d']
[0 1 2 3 5] [4]
['a' 'b' 'c' 'd' 'f'] ['e']
[0 1 2 3 4] [5]
['a' 'b' 'c' 'd' 'e'] ['f']


In [7]:
from sklearn.datasets import load_iris
from sklearn import svm

iris = load_iris()
# 查看数据大小
print(iris.data.shape)

# 建立svm线性分类器
clf = svm.LinearSVC()
# 用数据训练模型
clf.fit(iris.data,iris.target)
# 训练好后，输入新的数据进行预测
clf.predict([[5.0,3.6,1.3,0.25]])
# 查看训练好的模型参数
clf.coef_
# 得分越高，fit的训练效果越好
clf.score(iris.data,iris.target)

(150, 4)


/anaconda3/lib/python3.7/site-packages/sklearn/svm/base.py:931: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


0.9666666666666667